import type { Metadata } from "next";
import {ReactNode} from "react";
import Link from "next/link";
import '../app/globals.css';

export const metadata: Metadata = {
  title: "Next - routing & navigation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
      <html lang={'en'}>
      <body>
      <div>
          <header className="bg-gray-800 text-white p-4">
              <div className="container mx-auto flex justify-between items-center">
                  <div className="text-xl font-bold">My Website</div>
                  <nav>
                      <ul className="flex space-x-4">
                          <li><Link href="/" className="hover:text-gray-300">Home</Link></li>
                          <li><Link href="/about" className="hover:text-gray-300">About</Link></li>
                          <li><Link href="/services" className="hover:text-gray-300">Services</Link></li>
                          <li><Link href="/contact" className="hover:text-gray-300">Contact</Link></li>
                          <li><Link href="/teams" className="hover:text-gray-300">Teams</Link></li>
                      </ul>
                  </nav>
              </div>
          </header>

          <main className="container mx-auto py-8 px-4">
              {children}
          </main>

          <footer className="bg-gray-800 text-white p-4 mt-8">
              <div className="container mx-auto text-center">
                  &copy; 2024 My Website. All rights reserved.
              </div>
          </footer>
      </div>
      </body>
      </html>
  );
}
